local opt = vim.opt
vim.g.mapleader      = " "
vim.g.maplocalleader = " "
opt.number         = true
opt.relativenumber = true
opt.tabstop        = 4
opt.shiftwidth     = 4
opt.expandtab      = true
opt.smartindent    = true
opt.termguicolors  = true
opt.signcolumn     = "yes"
opt.cursorline     = true
opt.scrolloff      = 8
opt.sidescrolloff  = 8
opt.wrap           = false
opt.colorcolumn    = "100"
opt.hlsearch       = false
opt.incsearch      = true
opt.ignorecase     = true
opt.smartcase      = true
opt.splitright     = true
opt.splitbelow     = true
opt.swapfile       = false
opt.backup         = false
opt.undofile       = true
opt.undodir        = vim.fn.expand("~/.local/share/nvim/undo")
opt.updatetime     = 250
opt.timeoutlen     = 400
opt.mouse          = "a"
-- System clipboard fix: all yanks/pastes use system clipboard
opt.clipboard      = "unnamedplus"
opt.completeopt    = "menuone,noselect"
opt.pumheight      = 10
opt.showmode       = false
opt.laststatus     = 3
opt.foldmethod     = "expr"
opt.foldexpr       = "nvim_treesitter#foldexpr()"
opt.foldenable     = false
vim.g.loaded_netrw       = 1
vim.g.loaded_netrwPlugin = 1
