require("neo-tree").setup({
  close_if_last_window=true,popup_border_style="rounded",
  enable_git_status=true,enable_diagnostics=true,
  default_component_configs={
    indent={indent_size=2,padding=1,with_markers=true,
      indent_marker="│",last_indent_marker="└",
      with_expanders=true,expander_collapsed="",expander_expanded=""},
    icon={folder_closed="",folder_open="",folder_empty="ﰊ",default="*"},
    modified={symbol="[+]"},
    git_status={symbols={
      added="",modified="",deleted="✖",renamed="",
      untracked="",ignored="",unstaged="",staged="",conflict="",
    }},
  },
  window={
    position="left",width=35,
    mappings={
      ["<space>"]={      "toggle_node",nowait=false},
      ["<cr>"]   =       "open",
      ["P"]      =       {"toggle_preview",config={use_float=true}},
      ["S"]      =       "open_split",
      ["s"]      =       "open_vsplit",
      ["t"]      =       "open_tabnew",
      ["C"]      =       "close_node",
      ["z"]      =       "close_all_nodes",
      ["Z"]      =       "expand_all_nodes",
      ["a"]      =       {"add",config={show_path="none"}},
      ["A"]      =       "add_directory",
      ["d"]      =       "delete",
      ["r"]      =       "rename",
      ["y"]      =       "copy_to_clipboard",
      ["x"]      =       "cut_to_clipboard",
      ["p"]      =       "paste_from_clipboard",
      ["c"]      =       "copy",
      ["m"]      =       "move",
      ["q"]      =       "close_window",
      ["R"]      =       "refresh",
      ["?"]      =       "show_help",
      ["H"]      =       "toggle_hidden",
    },
  },
  filesystem={
    filtered_items={visible=false,hide_dotfiles=false,hide_gitignored=false,
      hide_by_name={".DS_Store","thumbs.db"}},
    follow_current_file={enabled=true},
    group_empty_dirs=false,
    hijack_netrw_behavior="open_default",
    use_libuv_file_watcher=true,
  },
  buffers={follow_current_file={enabled=true},group_empty_dirs=true,show_unloaded=true},
  git_status={window={position="float"}},
})
