#!/bin/bash

option=$(printf "🌐 Google\n🎥 YouTube\n👽 Reddit\n🤖 ChatGPT" | dmenu -i -p "Search on:")

case "$option" in
	    "🌐 Google")
		            query=$(dmenu -p "Google Search:")
			            [ -n "$query" ] && chromium "https://www.google.com/search?q=$(echo $query | sed 's/ /+/g')"
				            ;;
					        "🎥 YouTube")
							        query=$(dmenu -p "YouTube Search:")
								        [ -n "$query" ] && chromium "https://www.youtube.com/results?search_query=$(echo $query | sed 's/ /+/g')"
									        ;;
										    "👽 Reddit")
											            query=$(dmenu -p "Reddit Search:")
												            [ -n "$query" ] && chromium "https://www.reddit.com/search/?q=$(echo $query | sed 's/ /+/g')"
													            ;;
														        "🤖 ChatGPT")
																        chromium "https://chatgpt.com/?temporary-chat=true"
																	        ;;
																		    *)
																			            exit 1
																				            ;;
																			    esac

