#!/bin/sh

wall=$(find ~/Pictures/wallpapers -type f \( -name "*.jpg" -o -name "*.png" \) | shuf -n 1)

/home/sayooj/.config/suckless/scripts/dwmbar &


wal -c

wal -i "$wall"
dunst &
xwallpaper --zoom "$wall"
xdotool key super+F5


