#!/bin/bash

QUERY=$(printf "" | dmenu -p "YouTube Search: ")
CON=$(echo "$QUERY" | tr " " "+")

if [[ $(echo "$CON" | wc -c) -gt 1 ]]; then
    chromium "https://www.youtube.com/results?search_query=$CON"
fi

